# Generated by Django 3.2.9 on 2021-11-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='platform',
            field=models.CharField(default=0, max_length=10, verbose_name='Путь номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='station',
            field=models.CharField(default=0, max_length=100, verbose_name='Вокзал'),
            preserve_default=False,
        ),
    ]
